apiVersion: v1
kind: Service
metadata:
  name: picas-go-service
  labels:
    app: picas-go
spec:
  selector:
    app: picas-go
  type: NodePort
  ports:
    - nodePort: 31234
      port: 8081
      protocol: TCP
      targetPort: 8081
