name: Create Release Notes

on:
  schedule:
    - cron: "0 0 * * 2 TZ=America/New_York"
  workflow_dispatch:

jobs:
  create-release-note:
    permissions:
      contents: write
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Notes
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const date = new Date();
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: `v${date.toISOString().slice(0, 7).replace(/-/g, '.')}-rc`,
              generate_release_notes: true
            });
